force-app/main/default/objects/EMPLOYEE__c/EMPLOYEE__c.object-meta.xml
<CustomObject>
    <description>This Object is for Employee of the Company</description>
    <label>Employee</label>
    <nameField>
        <label>EMPLOYEE  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EMPLOYEE__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <description>This Field Contains the Date Of Birth of The Employee</description>
    <inlineHelpText>Date Of Birth Of The Employee</inlineHelpText>
    <label>Date of Birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMPLOYEE__c/fields/Date_of_Joining__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Joining__c</fullName>
    <description>This filed having the  Joining date of the employee</description>
    <inlineHelpText>Joining date of the employee</inlineHelpText>
    <label>Date of Joining</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMPLOYEE__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>This Field Contains the first name of employee</description>
    <inlineHelpText>First name of the employee</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMPLOYEE__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>This Field Contains the Last name of the Employee</description>
    <inlineHelpText>Last Name of the employee</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMPLOYEE__c/fields/Resignation_Date__c.field-meta.xml
<CustomField>
    <fullName>Resignation_Date__c</fullName>
    <description>This field having the date of resignation of the employee</description>
    <inlineHelpText>Resignation date of the employee</inlineHelpText>
    <label>Resignation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMPLOYEE__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <description>This field having zip code which is a part of the address</description>
    <inlineHelpText>Zip code of the employee address</inlineHelpText>
    <label>Zip</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SecurityTest.cls
@isTest
public class SecurityTest {
   public static testMethod void testRunAs() {
       EMPLOYEE__c emp = new EMPLOYEE__c(
       	Name ='somesome',
           First_Name__c= 'Seum',
           Last_Name__c ='Srum',
           Date_of_Birth__c = Date.valueOf(System.now().addYears(-22))  ,
           Date_of_Joining__c = Date.valueOf(System.now()),
           Zip__c = '422002',
           Resignation_Date__c = Date.valueOf(System.now().addMonths(4))
       );
       User u = new User(Id = '005dL00000zlZSNQA2');
        System.runAs(u) {
            insert emp;
            System.debug(emp);
          }
    }
}